### ISSUE TITLE
Eight *.test.ts files build a complete PullRequests literal and now miss editBody (src/start/pr-lifecycle.test.ts, sr...

### ISSUE THREAD

**Issue by marcostomatti** [open-tomato/rafa#43]
An out-of-scope bug a rafa task session reported. The loop filed it and dispatches no task for it: a plan that wants it fixed declares a task.

## What

```
Eight *.test.ts files build a complete PullRequests literal and now miss editBody (src/start/pr-lifecycle.test.ts, src/commands/pr/{merge,merge-driven,view,list,current,show,pr-context}.test.ts). No gate catches it because tsconfig.json excludes test files; each needs one refuse('editBody') line.
```

## Artifact

```
error TS2741: Property 'editBody' is missing in type
```

## Plan

```
rafa-21-changelog-and-release
```

## Task

```
Add `editBody` to the `PullRequests` port in `src/pr/types.ts`, to the `gh` adapter in `src/pr/gh.ts` and to the fake in `src/pr/gh-fake.ts` with its route row, with their unit tests
```

## Feedback

```
Added `editBody` to the pull request port, to the `gh` adapter and to the recorded fake,
with unit tests for all three. The adapter sends `gh pr edit <n> --body <text>` (body as one
argv element, never interpolated) and answers `Promise<void>`, reading the exit code alone —
`gh pr edit`'s success output was never recorded, a write being what `gh-fake-shapes.ts`
cannot read off a repository, so the fake writes nothing either and replaces the stored body.
A missing pull request THROWS here where `get` answers null, and the port note now splits
reads from writes on that rule.
Measured rather than asserted: eight mutations were driven, three of `src/pr/gh.ts`, three of
`src/pr/gh-fake.ts` and two of `src/pr/types.ts`, one run each over the covering file, each
module restored byte-identical (sha256) after every run and each mutation reddening at least
one case; the three test module notes carry the lists as the runs produced them.
Gates at this working tree: `bunx tsc --noEmit` exit 0; `bunx eslint .` exit 0;
`scripts/control-byte-gate` exit 0 over 606 files; `bun test` exit 1 with 6563 pass, 1 skip,
1 fail — the documented live-sibling parity case, which is green on its own (4 pass, 0 fail)
and whose input file had been written to one second earlier by another run.
```
